version: "3.8"
services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "${REDIS_PASSWORD:-redis_password}"]
    deploy:
      resources:
        limits:
          memory: 256M
    networks:
      - mobidrawer-network
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD:-redis_password}", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./IE213Backend
      dockerfile: Dockerfile
      args:
        MAVEN_OPTS: "-Xmx512m"
    container_name: mobidrawer-backend
    ports:
      - "8080:8080"
    environment:
      # MongoDB connection settings
      - SPRING_DATA_MONGODB_URI=${MONGODB_URI:-mongodb+srv://laidaynao901:S2bMWiZCDIqhES1Q@cluster0.qv15ecd.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0}
      - SPRING_DATA_MONGODB_DATABASE=${MONGODB_DATABASE:-IE213}
      # Redis connection settings with password
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - SPRING_DATA_REDIS_PASSWORD=${REDIS_PASSWORD:-redis_password}
      # Production settings
      - JAVA_OPTS=-XX:+UseG1GC -XX:MaxGCPauseMillis=100 -XX:+UseStringDeduplication -Xms256m -Xmx512m
      - SPRING_PROFILES_ACTIVE=production
    depends_on:
      redis:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 512M
    restart: always
    networks:
      - mobidrawer-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: mobidrawer-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://backend:8080
    depends_on:
      - backend
    deploy:
      resources:
        limits:
          memory: 1G
    restart: always
    networks:
      - mobidrawer-network

volumes:
  redis_data:
    driver: local
  mongodb_data:
    driver: local

networks:
  mobidrawer-network:
    driver: bridge