version: "3.8"
services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]
    deploy:
      resources:
        limits:
          memory: 256M
    networks:
      - mobidrawer-network

  backend:
    build:
      context: ./IE213Backend
      dockerfile: Dockerfile
    container_name: mobidrawer-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/mobidrawer
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    depends_on:
      - redis
      - mongodb
    deploy:
      resources:
        limits:
          memory: 512M
    restart: always
    networks:
      - mobidrawer-network

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: mobidrawer-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    deploy:
      resources:
        limits:
          memory: 2G
    restart: always
    networks:
      - mobidrawer-network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    deploy:
      resources:
        limits:
          memory: 384M
    restart: always
    networks:
      - mobidrawer-network

volumes:
  redis_data:
    driver: local
  mongodb_data:
    driver: local

networks:
  mobidrawer-network:
    driver: bridge
